In [6]:
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials

In [2]:
!pip install gspread

Collecting gspread
  Downloading https://files.pythonhosted.org/packages/35/06/8005de56693b17aab7eb6aa7b27e414efb23a5021d098e3597303bba92fc/gspread-5.2.0-py3-none-any.whl
Collecting google-auth>=1.12.0 (from gspread)
  Downloading https://files.pythonhosted.org/packages/66/12/eb8e0254e84f47deb4bd65858aef26f93fb4786091442d6bd2e86a5843d3/google_auth-2.6.0-py2.py3-none-any.whl (156kB)
Collecting google-auth-oauthlib>=0.4.1 (from gspread)
  Downloading https://files.pythonhosted.org/packages/77/62/be9811606c4163068e8e5076864356881d3456b5c192997dee4e9a23acd6/google_auth_oauthlib-0.5.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from google-auth>=1.12.0->gspread) (1.12.0)
Collecting cachetools<6.0,>=2.0.0 (from google-auth>=1.12.0->gspread)
  Downloading https://files.pythonhosted.org/packages/19/99/ace1769546388976b45e93445bb04c6df95e96363f03fbb56f916da5ebde/cachetools-5.0.0-py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.12.0->gspread)
  Downloading https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl (155kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.6" (from google-auth>=1.12.0->gspread)
  Downloading https://files.pythonhosted.org/packages/30/ab/8fd9e88e6fa5ec41afca995938bbefb72195278e0cfc5bd76a4f29b23fb2/rsa-4.8-py3-none-any.whl
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.4.1->gspread)
  Downloading https://files.pythonhosted.org/packages/6f/bb/5deac77a9af870143c684ab46a7934038a53eb4aa975bc0687ed6ca2c610/requests_oauthlib-1.3.1-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread)
  Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
Requirement already satisfied: requests>=2.0.0 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.22.0)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread)
  Downloading https://files.pythonhosted.org/packages/1d/46/5ee2475e1b46a26ca0fa10d3c1d479577fde6ee289f8c6aa6d7ec33e31fd/oauthlib-3.2.0-py3-none-any.whl (151kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.24.2)
Installing collected packages: cachetools, pyasn1, pyasn1-modules, rsa, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, gspread
Successfully installed cachetools-5.0.0 google-auth-2.6.0 google-auth-oauthlib-0.5.0 gspread-5.2.0 oauthlib-3.2.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.1 rsa-4.8

In [3]:
!pip install --upgrade google-api-python-client oauth2client

Collecting google-api-python-client
  Downloading https://files.pythonhosted.org/packages/da/a0/214373eccbf3bb65327bcfbde32c95f06047126c9591319541d90dc57bd1/google_api_python_client-2.39.0-py2.py3-none-any.whl (8.2MB)
Collecting oauth2client
  Downloading https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl (98kB)
Collecting google-auth-httplib2>=0.1.0 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/ba/db/721e2f3f32339080153995d16e46edc3a7657251f167ddcb9327e632783b/google_auth_httplib2-0.1.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: google-auth<3.0.0dev,>=1.16.0 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from google-api-python-client) (2.6.0)
Collecting google-api-core<3.0.0dev,>=1.21.0 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/3e/3b/2980076219eee0f6d821c023823be371d4814b1d12a8b3d09323949e92de/google_api_core-2.7.1-py3-none-any.whl (114kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/81/c0/7461b49cd25aeece13766f02ee576d1db528f1c37ce69aee300e075b485b/uritemplate-4.1.1-py2.py3-none-any.whl
Collecting httplib2<1dev,>=0.15.0 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/59/0f/29725a9caf4b2618f524e0f28e2bda91aca8f880123ec77426ede6ea1ea4/httplib2-0.20.4-py3-none-any.whl (96kB)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.0.5 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from oauth2client) (0.2.8)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.7 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from oauth2client) (0.4.8)
Requirement already satisfied, skipping upgrade: rsa>=3.1.4 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from oauth2client) (4.8)
Requirement already satisfied, skipping upgrade: six>=1.6.1 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from oauth2client) (1.12.0)
Requirement already satisfied, skipping upgrade: cachetools<6.0,>=2.0.0 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (5.0.0)
Requirement already satisfied, skipping upgrade: requests<3.0.0dev,>=2.18.0 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.22.0)
Collecting googleapis-common-protos<2.0dev,>=1.52.0 (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/50/a9/6c76954ad5ee88c749407b282e5dfa724e3bd3065a069bcbe6a3da08a3e3/googleapis_common_protos-1.55.0-py2.py3-none-any.whl (212kB)
Collecting protobuf>=3.12.0 (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/b3/41/5e2dfb15fdae38be5dd62be30f9fd40c57e50bd56ee2c276f6230c57a3ad/protobuf-3.19.4-cp37-cp37m-win_amd64.whl (896kB)
Requirement already satisfied, skipping upgrade: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2; python_version > "3.0" in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client) (2.4.2)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2019.9.11)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (1.24.2)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (3.0.4)
Installing collected packages: httplib2, google-auth-httplib2, protobuf, googleapis-common-protos, google-api-core, uritemplate, google-api-python-client, oauth2client
Successfully installed google-api-core-2.7.1 google-api-python-client-2.39.0 google-auth-httplib2-0.1.0 googleapis-common-protos-1.55.0 httplib2-0.20.4 oauth2client-4.1.3 protobuf-3.19.4 uritemplate-4.1.1

In [8]:
aa_codebook=pd.read_excel("Survey Codebook_revised.xlsx")

In [10]:
aa_codebook

,Section,Survey Question (Label),variable name
0,NaN,NaN,NaN
1,A. Client Demographics,NaN,NaN
2,NaN,Surveyor/Enumerator name,cd_enum_name
3,NaN,Gender,cd_gender
4,NaN,Name/Clients name,cd_name
...,...,...,...
94,NaN,if you are not in a saving group and you are s...,liv_sgno_saveany_hw
95,NaN,if other saving mode specify,liv_sgno_saveany_hw_otr
96,NaN,What is your second income resource?,liv_second_incsource
97,NaN,How much money yourself do you save per month?,liv_sgno_saveany_hwmuch
98,NaN,Do you feel that there is a change in househol...,liv_livingcond_change

In [14]:
aa_endline_Test_revised=pd.read_excel("Kak_endline_Test_revised.xlsx")

In [15]:
aa_endline_Test_revised

,unique_id,cd_gender,cd_nationality,cd_strata,cd_age,client_location,bd_location,cd_enum_name,consent,consent_yesno,...,bd_biz_failure_reasn_5,bd_biz_failure_reasn_6,bd_biz_failure_reasn_7,bd_biz_failure_reasn_8,bd_biz_failure_reasn_otr,refusal,otherpecify,end_comment,end_commentyes,thanks
0,7,Male,Kenyan,Host community entrepreneur,36,Kakuma town,Kakuma town,Khaltom Abdallar Abakar,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
1,8,Female,Kenyan,Host community entrepreneur,32,Kakuma town,Kakuma town,Losike Josephat,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,God bless AEC,NaN
2,PART/KE16012104001,Male,Congolese,Refugee,25,Kakuma 2,Kakuma 2,Losike Josephat,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
3,PART/KE16012104002,Male,Sudanese,Refugee,39,Kakuma 3,Kakuma 3,Ramla Abdullahi,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I will be looking forward to your help.,NaN
4,PART/KE16012104003,Female,Somali,Refugee,35,Kakuma 3,Kakuma 3,Ramla Abdullahi,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,PART/KE16012104896,Female,Somali,Refugee,45,Kakuma 3,Kakuma 3,Losike Josephat,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
533,PART/KE16012104897,Female,Kenyan,Host,26,Kakuma Town,Kakuma Town,David Chol,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
534,PART/KE16012104898,Male,Somali,Refugee,20,Kakuma 3,Kakuma 3,Losike Josephat,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
535,PART/KE16012104899,Female,Somali,Refugee,47,Kakuma 3,Kakuma 3,Losike Josephat,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
536,PART/KE16012104900,Female,Somali,Refugee,30,Kakuma 2,Kakuma 2,David Chol,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN

In [17]:
aa_Baseline_Test_revised=pd.read_excel("Kak_Baseline_Test_revised.xlsx")

In [27]:
df=aa_Baseline_Test_revised

In [1]:
df.is

SyntaxError: invalid syntax (<ipython-input-1-e5b32670040e>, line 1)

In [15]:
import pyodbc
import pandas as pd
# Connection to db
sql_conn = pyodbc.connect(Trusted_Connection='Yes', DRIVER='{SQL Server}', SERVER='IT-MAXIMET\TSTDB', DATABASE='TestDB',\
                      UID='testdba', PWD='testdba')

In [18]:
dfi = pd.read_sql("select * from [TESTDB].[info]", sql_conn)

TypeError: 'tuple' object is not callable

In [13]:
sql_conn

In [18]:
import pymysql
import pandas as pd
conni=pymysql.connect(host='localhost',port=int(3306),user='root',passwd='maxo',db='test_INKOMOKO_db')

#dfii=pd.read_sql_query("SELECT * FROM collations limit 2",conni)

#print(dfii)

In [2]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="maxo"
)

mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE test_INKOMOKO_db")

In [1]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (8.0.28)
Requirement already satisfied: protobuf>=3.0.0 in c:\users\m.tuyisenge\appdata\local\continuum\anaconda3\lib\site-packages (from mysql-connector-python) (3.19.4)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import mysql.connector

mydb = mysql.connector.connect(
 host="localhost",
  user="root",
  password="maxo"
)

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

('information_schema',)
('mysql',)
('performance_schema',)
('sys',)
('test_inkomoko_db',)

In [24]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="maxo",
  database="test_INKOMOKO_db"
)

In [30]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="maxo",
database="test_inkomoko_db"
)
mycursor = mydb.cursor() 
mycursor.execute('create table baseline
('
uid	                           int primary key,
bd_earner_only                  varchar(250),
bd_members_respfor				varchar(250),
bd_bizsector					varchar(250),
e_total_employees				varchar(250),
e_fulltime_employees			varchar(250),
e_parttime_employees			varchar(250),
e_casual_employees				varchar(250),
e_male_employees				varchar(250),
e_female_employees				varchar(250),
e_related_employees				varchar(250),
e_refugees_employees			varchar(250),
Howmanyemployeesarefromthe		varchar(250),
sr_bank_account					varchar(250),
sr_pri_inc_sourcs				varchar(250),
sr_access_newfunds				varchar(250),
IfYesinQ31howhaveyouacce		varchar(250),
sr_access						varchar(250),
sr_access_1						varchar(250),
sr_access_2						varchar(250),
sr_access_3						varchar(250),
sr_access_4						varchar(250),
sr_access_5						varchar(250),
sr_access_6						varchar(250),
sr_access_7						varchar(250),
sr_access_8						varchar(250),
sr_access_9						varchar(250),
sr_access_no					varchar(250),
Onaveragehowmanycustomersd		varchar(250),
sr_customers_hwmny				varchar(250),
OUTLIERCHECKONTHENUMBEROFC		varchar(250),
sr_customers_main				varchar(250),
sr_records_keepb				varchar(250),
sr_mnthly_sales_total			varchar(250),
OUTLIERCHECKONTHEAVERAGEMON		varchar(250),
sr_fluctuations					varchar(250),
sr_revstreams_most				varchar(250),
sr_revstreams_least				varchar(250),
BI								varchar(250),
BJ								varchar(250),
BK								varchar(250),
BL								varchar(250),
Onascaleof1to5where1me			varchar(250),
knwrate_sales					varchar(250),
knwrate_ops_mgt					varchar(250),
knwrate_invent_mgt				varchar(250),
knwrate_bkeeping				varchar(250),
knwrate_cashflow				varchar(250),
skill_imprv1					varchar(250),
skill_imprv2	s				varchar(250),
kill_imprv3	skill_imprv4		varchar(250),
Howmanymealsdoesyourhouseho		varchar(250),
liv_meals_number_base			varchar(250),
Inthelast4monthsdidyoubu		varchar(250),
liv_assetsbght_4mnths			varchar(250),
liv_cookingfuel	CB				varchar(250),
CC	liv_expnseschl_3mnths		varchar(250),
liv_expnsecooking				varchar(250),
liv_expnsehhclthng				varchar(250),
liv_expnserent					varchar(250),
liv_expnsetrans_comm			varchar(250),
aec_knowledge					varchar(250))')'

SyntaxError: EOL while scanning string literal (<ipython-input-30-b39cafe07c49>, line 8)

In [14]:
model.export_srcpkg(platform, toolchain, "mymodel_pkg.zip", "mymodel.dylib")

NameError: name 'model' is not defined

In [29]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="maxo",
database="test_INKOMOKO_db"
)

In [28]:

mycursor = mydb.cursor()
mycursor.execute("create table baseline (
uid int primarykey,
bd_earner_only varchar(250),
bd_members_respfor varchar(250),
bd_bizsector varchar(250),
e_total_employees varchar(250),
e_fulltime_employees varchar(250),
e_parttime_employees varchar(250),
e_casual_employees varchar(250),
e_male_employees varchar(250),
e_female_employees varchar(250),
e_related_employees varchar(250),
e_refugees_employees varchar(250),
Howmanyemployeesarefromthe	varchar(250),
sr_bank_account	varchar(250),
sr_pri_inc_sourcs varchar(250),
sr_access_newfunds varchar(250),
IfYesinQ31howhaveyouacce varchar(250),
sr_access	varchar(250),
sr_access_1	varchar(250),
sr_access_2	varchar(250),
sr_access_3	varchar(250),
sr_access_4	varchar(250),
sr_access_5	varchar(250),
sr_access_6	varchar(250),
sr_access_7	varchar(250),
sr_access_8	varchar(250),
sr_access_9	varchar(250),
sr_access_no varchar(250),
Onaveragehowmanycustomersd varchar(250),
sr_customers_hwmny varchar(250),
OUTLIERCHECKONTHENUMBEROFC varchar(250),
sr_customers_main varchar(250),
sr_records_keepb varchar(250),
sr_mnthly_sales_total varchar(250),
OUTLIERCHECKONTHEAVERAGEMON	 varchar(250),
sr_fluctuations	 varchar(250),
sr_revstreams_most varchar(250),
sr_revstreams_least	varchar(250),
BI varchar(250),
BJ varchar(250),
BK varchar(250),
BL varchar(250),
Onascaleof1to5where1me varchar(250),
knwrate_sales varchar(250),
knwrate_ops_mgt	varchar(250),
knwrate_invent_mgt	varchar(250),
knwrate_bkeeping varchar(250),
knwrate_cashflowvarchar(250),
skill_imprv1 varchar(250),
skill_imprv2 varchar(250),
skill_imprv3 varchar(250),
skill_imprv4 varchar(250),
Howmanymealsdoesyourhouseho	varchar(250),
liv_meals_number_base varchar(250),
Inthelast4monthsdidyoubu varchar(250),
liv_assetsbght_4mnths varchar(250),
liv_cookingfuel	CB varchar(250),
CC	liv_expnseschl_3mnths varchar(250),
liv_expnsecooking varchar(250),
liv_expnsehhclthng varchar(250),
liv_expnserent varchar(250),
liv_expnsetrans_comm varchar(250),
aec_knowledge varchar(250)");

SyntaxError: EOL while scanning string literal (<ipython-input-28-066d1690a050>, line 8)